---
AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS CloudFormation template
Resources:
  User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub ${AWS::StackName}-user
      Path: "/"
