#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

aws cloudformation create-stack \
      --stack-name $PROJECT_NAME \
      --template-body file://$DIR/cloudformation.yml \
            --capabilities CAPABILITY_IAM \
      --capabilities CAPABILITY_NAMED_IAM && \

      aws cloudformation wait stack-create-complete \
        --stack-name $PROJECT_NAME
